# Generated by Django 4.0.4 on 2022-05-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Название категории товаров')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'db_table': 'Категории товаров',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание товара')),
                ('price', models.FloatField(max_length=10, verbose_name='Цена товара')),
                ('number_of_items', models.IntegerField(max_length=5, verbose_name='Количество товара в наличии')),
                ('items_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_api.categories', verbose_name='Категория товаров')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'Товары',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlg_user_id', models.CharField(max_length=10, verbose_name='ID пользователя телеграм')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('pay_status', models.BooleanField(db_index=True, default=False, verbose_name='Статус оплаты')),
                ('execution_status', models.BooleanField(db_index=True, default=False, verbose_name='Статус выполнения заказа')),
                ('order_items', models.CharField(max_length=4000, verbose_name='Товара из заказа')),
                ('result_orders_price', models.FloatField(verbose_name='Итоговая цена заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Заказы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_number_in_basket', models.IntegerField(max_length=5, verbose_name='Количество данного товара в корзине')),
                ('user_tlg_id', models.CharField(max_length=20, verbose_name='ID пользователя телеграм')),
                ('items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_api.items', verbose_name='ID товара')),
            ],
            options={
                'verbose_name': 'Товары в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'db_table': 'Товары в корзине',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MediaForItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(blank=True, max_length=5000, null=True, upload_to='files/%Y/%m/%d')),
                ('for_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_api.items', verbose_name='Для товара')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
                'db_table': 'Медиа для товаров',
                'ordering': ['id'],
            },
        ),
    ]
