# Generated by Django 4.0.4 on 2022-05-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='number_of_items',
            field=models.IntegerField(verbose_name='Количество товара в наличии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.TextField(max_length=4000, verbose_name='Товары из заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tlg_user_id',
            field=models.CharField(max_length=20, verbose_name='ID пользователя телеграм'),
        ),
        migrations.AlterField(
            model_name='orderbasket',
            name='items_number_in_basket',
            field=models.IntegerField(verbose_name='Количество данного товара в корзине'),
        ),
    ]
