# Generated by Django 4.0.4 on 2022-06-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0002_alter_items_number_of_items_alter_order_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image_for_items_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID картинки для товара'),
        ),
    ]
