# Generated by Django 4.0.4 on 2022-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0004_alter_orderbasket_items_number_in_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbasket',
            name='items_number_in_basket',
            field=models.IntegerField(default=1, verbose_name='Количество данного товара в корзине'),
        ),
    ]
