# Generated by Django 4.0.4 on 2022-06-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0005_alter_orderbasket_items_number_in_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tlg_user_id',
            new_name='user_tlg_id',
        ),
    ]
