# Generated by Django 4.0.4 on 2022-06-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0006_rename_tlg_user_id_order_user_tlg_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-datetime'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
