# Generated by Django 4.0.4 on 2022-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0012_paidorder_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderarchive',
            name='user_tlg_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID пользователя телеграм'),
        ),
    ]
