# Generated by Django 4.0.4 on 2022-06-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0014_alter_order_user_tlg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Товары из заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='result_orders_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Итоговая цена заказа'),
        ),
    ]
