# Generated by Django 4.0.4 on 2022-06-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0015_alter_order_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.TextField(default=1, max_length=4000, verbose_name='Товары из заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='result_orders_price',
            field=models.FloatField(default=1, verbose_name='Итоговая цена заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user_tlg_id',
            field=models.CharField(default=1, max_length=20, verbose_name='ID пользователя телеграм'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderarchive',
            name='user_tlg_id',
            field=models.CharField(default=1, max_length=20, verbose_name='ID пользователя телеграм'),
            preserve_default=False,
        ),
    ]
